// <auto-generated />
using BAOCAO2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAOCAO2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121133321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BAOCAO2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Điện thoại Samsung A55",
                            Price = 8000000.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop Asus VivoBook",
                            Price = 14500000.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chuột Logitech G102",
                            Price = 350000.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bàn phím cơ AKKO 3068",
                            Price = 1500000.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tai nghe Sony WH-CH510",
                            Price = 1250000.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Loa Bluetooth JBL Go 3",
                            Price = 990000.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Máy tính bảng Lenovo M10",
                            Price = 5200000.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Màn hình LG 24 inch",
                            Price = 3200000.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ổ cứng SSD Kingston 480GB",
                            Price = 850000.0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pin dự phòng Xiaomi 20000mAh",
                            Price = 650000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
